name: Terraform Workflow

on:
  push:
    branches:
      - main

# permissions:
#       id-token: write
#       contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    # env:
    #   export ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #   export ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    #   export ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    #   export ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBCRIPTION_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        run: az login
  
        # run:  az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
        
        # uses: azure/login@v1
        # with:
        #   client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #   tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #   subscription-id: ${{ secrets.AZURE_SUBCRIPTION_ID }}
        
        # with:
        #   creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      # Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
