name: Terraform Workflow

on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login 
        run: az login --use-device-code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Check Drift
        run: echo "::set-output name=drift_detected::$(grep 'No changes' tfplan | wc -l)"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy Plan
        run: terraform plan -destroy -out=tfDestroyPlan

      - name: Save Terraform Destroy Plan
        uses: actions/upload-artifact@v2
        with:
          name: tfDestroyPlan
          path: tfDestroyPlan

  destroy_infra:
    runs-on: ubuntu-latest
    needs: deploy_infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Azure login
        run: az login --use-device-code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0

      - name: Terraform Init
        run: terraform init

      # Download saved plan from artifacts  
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfDestroyPlan
      
      - name: Terraform Destroy
        run: terraform apply -auto-approve tfDestroyPlan