name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
      #   run: az login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      # Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply2

      # aks kubeconfig
      # - name: Set up kubectl
      #   run: cp k8s/config ~/.kube/config

      # deploy to aks
      # - name: Deploy to AKS
      #   run: |
      #     kubectl apply -f k8s/deployment.yaml
      #     kubectl apply -f k8s/service.yaml

      # # get pods
      # - name: Validate Deployment
      #   run: kubectl get pods

      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
